---
name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - run: echo "no name"

      # - name: longer-step
        # run: apt update

      # - run: apt install -y neovim

  my-second-job:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: my-other-step
        run: echo "foobar"

